[v1]
"bat 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"cargo-alfred 0.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-alfred"]
"cargo-bump 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bump"]
"cargo-criterion 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-criterion"]
"cargo-outdated 0.9.1 (git+https://github.com/kbknapp/cargo-outdated#2415986d19a57ce185e3b3f274fa17b2a3556fca)" = ["cargo-outdated"]
"du-dust 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"eva 0.2.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["eva"]
"fd-find 7.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"findomain 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["findomain"]
"hexyl 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hexyl"]
"hid-cli 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hid-cli"]
"hist-cli 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["hist"]
"nu 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["nu", "nu_plugin_average", "nu_plugin_binaryview", "nu_plugin_edit", "nu_plugin_embed", "nu_plugin_inc", "nu_plugin_insert", "nu_plugin_ps", "nu_plugin_read", "nu_plugin_skip", "nu_plugin_str", "nu_plugin_sum", "nu_plugin_sys", "nu_plugin_textview"]
"read-process-memory 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["test"]
"ripgrep 11.0.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"rn-xlsx2csv 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xlsx2csv"]
"rustpython 0.1.2 (git+https://github.com/RustPython/RustPython#ab9ca950e215539952e88a8b4e713ecb5b1187fb)" = ["rustpython"]
"zellij 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["zellij"]
