[v1]
"bat 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"cargo-bump 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bump"]
"cargo-outdated 0.9.1 (git+https://github.com/kbknapp/cargo-outdated#2415986d19a57ce185e3b3f274fa17b2a3556fca)" = ["cargo-outdated"]
"fd-find 7.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"hexyl 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hexyl"]
"nu 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["nu", "nu_plugin_average", "nu_plugin_binaryview", "nu_plugin_edit", "nu_plugin_embed", "nu_plugin_inc", "nu_plugin_insert", "nu_plugin_ps", "nu_plugin_read", "nu_plugin_skip", "nu_plugin_str", "nu_plugin_sum", "nu_plugin_sys", "nu_plugin_textview"]
"ripgrep 11.0.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"rn-xlsx2csv 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xlsx2csv"]
